"""add_strength_and_onboarding_flag_to_company

Revision ID: 0b6150659d8a
Revises: e89ebbd26462
Create Date: 2026-05-02 20:39:05.590169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6150659d8a'
down_revision: Union[str, None] = 'e89ebbd26462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('strength', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.execute("UPDATE companies SET onboarding_completed = FALSE")
    op.alter_column('companies', 'onboarding_completed', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'onboarding_completed')
    op.drop_column('companies', 'strength')
    # ### end Alembic commands ###
