"""add_login_id_dept_fields_payroll_config

Revision ID: b4e2d77d9638
Revises: 87f6424590be
Create Date: 2026-05-02 16:32:15.399219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e2d77d9638'
down_revision: Union[str, None] = '87f6424590be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('pf_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('pf_ceiling', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hra_percent', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('conveyance_fixed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('medical_fixed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('professional_tax', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('tds_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('lta_annual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('overtime_rate_multiplier', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('working_days_per_month', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_configs_company_id'), 'payroll_configs', ['company_id'], unique=True)
    op.create_index(op.f('ix_payroll_configs_id'), 'payroll_configs', ['id'], unique=False)
    op.add_column('companies', sa.Column('short_code', sa.String(length=4), nullable=True))
    op.add_column('departments', sa.Column('manager_name', sa.String(length=150), nullable=True))
    op.add_column('departments', sa.Column('headcount', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('login_id', sa.String(length=25), nullable=True))
    op.create_index(op.f('ix_employees_login_id'), 'employees', ['login_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_login_id'), table_name='employees')
    op.drop_column('employees', 'login_id')
    op.drop_column('departments', 'headcount')
    op.drop_column('departments', 'manager_name')
    op.drop_column('companies', 'short_code')
    op.drop_index(op.f('ix_payroll_configs_id'), table_name='payroll_configs')
    op.drop_index(op.f('ix_payroll_configs_company_id'), table_name='payroll_configs')
    op.drop_table('payroll_configs')
    # ### end Alembic commands ###
