"""add_aadhar_number_to_employees

Revision ID: e89ebbd26462
Revises: a2713c2dd03a
Create Date: 2026-05-02 19:09:38.673435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e89ebbd26462'
down_revision: Union[str, None] = 'a2713c2dd03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('aadhar_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'aadhar_number')
    # ### end Alembic commands ###
